services:  

    prodigious_sonata_menu.factory:
        class: Prodigious\Sonata\MenuBundle\Factory\MenuFactor

    prodigious_sonata_menu.manager:
        class: Prodigious\Sonata\MenuBundle\Manager\MenuManager
        arguments: ["@doctrine.orm.entity_manager"]

    prodigious_sonata_menu.repo:
        class: Prodigious\Sonata\MenuBundle\Repository\MenuRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - Prodigious\Sonata\MenuBundle\Entity\Menu
    
    prodigious_sonata_menu_item.repo:
        class: Prodigious\Sonata\MenuBundle\Repository\MenuItemRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - Prodigious\Sonata\MenuBundle\Entity\MenuItem
    
    prodigious_sonata_menu.admin.menu:
        class: Prodigious\Sonata\MenuBundle\Admin\MenuAdmin
        arguments: [~, Prodigious\Sonata\MenuBundle\Entity\Menu, ProdigiousSonataMenuBundle:Menu]
        tags:
            - { name: sonata.admin, manager_type: orm, label: config.label_menu, group: config.label_menu, label_catalogue: ProdigiousSonataMenuBundle }
        calls:
            - [ setTranslationDomain, [ProdigiousSonataMenuBundle]]  
            - [ addChild, ['@prodigious_sonata_menu.admin.menu_item']]
            
    prodigious_sonata_menu.admin.menu_item:
        class: Prodigious\Sonata\MenuBundle\Admin\MenuItemAdmin
        arguments: [~, Prodigious\Sonata\MenuBundle\Entity\MenuItem, ProdigiousSonataMenuBundle:MenuItem]
        tags:
            - { name: sonata.admin, manager_type: orm, label: config.label_menu_item, group: config.label_menu, show_in_dashboard: false, label_catalogue: ProdigiousSonataMenuBundle  }
        calls:
            - [ setTranslationDomain, [ProdigiousSonataMenuBundle]]