<?php

namespace Prodigious\Sonata\MenuBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Prodigious\Sonata\MenuBundle\Entity\Menu;
use Prodigious\Sonata\MenuBundle\Entity\MenuItem;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
	/**
	 * Remove a menu
	 *
	 * @param \Prodigious\Sonata\MenuBundle\Entity\Menu $menu
	 */
	public function remove(Menu $menu)
	{
		$em = $this->getEntityManager();
		$conn = $em->getConnection();
		$conn->beginTransaction();

		try{
			
			foreach ($menu->getMenuItems as $menuItem) {
				$em->remove($menuItem);
			}

			$em->remove($menu);
			$em->flush();

			$conn->commit();

		} catch (\Exception $e) {
			$conn->rollBack();
			throw $e;
		}
	}

	/**
	 * Save a menu
	 *
	 * @param \Prodigious\Sonata\MenuBundle\Entity\Menu $menu
	 */
	public function save(Menu $menu)
	{
		$em = $this->getEntityManager();
		
		$em->persist($menu);

		$em->flush();
	}

	/**
	 * Save a menu
	 *
	 * @param int $id
	 */
	public function removeById($id)
	{
		$menu = $this->find($id);
		
		$this->remove($menu);
	}

	/**
	 * Get all menus
	 *
     * @return Menu[]
     */
    public function findAll()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT m FROM ProdigiousSonataMenuBundle:Menu m');

        return $query->getResult();
    }

    /**
	 * Get menu by id
	 *
     * @return Menu
     */
    public function findById($id)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT m FROM ProdigiousSonataMenuBundle:Menu m WHERE m.id = :id');
        $query->setParameter('id', $id);

        return $query->getOneOrNullResult();
    }

}
