<?php

namespace Prodigious\Sonata\MenuBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Prodigious\Sonata\MenuBundle\Model\MenuInterface;
use Prodigious\Sonata\MenuBundle\Model\MenuItemInterface;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
    /**
     * Remove a menu
     */
    public function remove(MenuInterface $menu)
    {
        $em = $this->getEntityManager();
        $conn = $em->getConnection();
        $conn->beginTransaction();

        try {
            foreach ($menu->getMenuItems as $menuItem) {
                $em->remove($menuItem);
            }

            $em->remove($menu);
            $em->flush();

            $conn->commit();
        } catch (\Exception $e) {
            $conn->rollBack();

            throw $e;
        }
    }

    /**
     * Save a menu
     */
    public function save(MenuInterface $menu)
    {
        $em = $this->getEntityManager();

        $em->persist($menu);

        $em->flush();
    }

    /**
     * Save a menu
     *
     * @param int $id
     */
    public function removeById($id)
    {
        $menu = $this->find($id);

        $this->remove($menu);
    }
}
